apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ include "mysql.fullname" . }}
spec:
  # storageClassName: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Release.Namespace }}
  storageClassName: {{ include "mysql.fullname" . }}-{{ .Release.Namespace }}
  accessModes:
    - {{ .Values.pv.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage }}

