apiVersion: v1
kind: Service
metadata:
  labels:
    # app: {{ .Release.Name }}-{{ .Chart.Name }}
    # name: {{ .Release.Name }}-{{ .Chart.Name }}
    app: {{ include "api.fullname" . }}
    name: {{ include "api.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    # app: {{ .Release.Name }}-{{ .Chart.Name }}
    app: {{ include "api.fullname" . }}
  type: {{ .Values.service.type }}

